#import <Foundation/Foundation.h>
#import <AVFoundation/AVFoundation.h>
#import <notify.h>

static const char *kWSBWeatherNotify = "com.sushibta.vmlspeedbubble.weather";
static NSString * const kWSBPayloadPath = @"/var/mobile/VMLWeatherPayload.plist";
static NSString * const kWSBLogPath = @"/var/mobile/VMLWeatherSpeech.txt";
static int gWSBToken = 0;
static AVSpeechSynthesizer *gWSBSpeech = nil;

static BOOL WSBIsSpringBoard(void){return [NSBundle.mainBundle.bundleIdentifier isEqualToString:@"com.apple.springboard"];}
static void WSBLog(NSString *format,...){va_list args;va_start(args,format);NSString *msg=[[NSString alloc]initWithFormat:format arguments:args];va_end(args);NSString *line=[NSString stringWithFormat:@"%@ | %@\n",[NSDate date],msg?:@""];NSData *data=[line dataUsingEncoding:NSUTF8StringEncoding];if(![[NSFileManager defaultManager]fileExistsAtPath:kWSBLogPath]){[data writeToFile:kWSBLogPath atomically:YES];return;}NSFileHandle *fh=[NSFileHandle fileHandleForWritingAtPath:kWSBLogPath];if(!fh)return;@try{[fh seekToEndOfFile];[fh writeData:data];[fh closeFile];}@catch(__unused NSException *e){}}
static BOOL WSBIsRain(NSInteger code){return (code>=51&&code<=57)||(code>=61&&code<=67)||(code>=80&&code<=82);}
static NSString *WSBSentence(NSString *name,double temp,NSInteger code){NSString *place=name.length?name:@"điểm đến";if(code==0)return [NSString stringWithFormat:@"Vị trí điểm đến %@ hiện tại trời nắng, nhiệt độ %.0f độ. Chú ý mang theo dù.",place,temp];if(WSBIsRain(code))return [NSString stringWithFormat:@"Vị trí điểm đến %@ hiện tại đang mưa, nhiệt độ %.0f độ. Chú ý mang theo áo mưa.",place,temp];if(code>=95)return [NSString stringWithFormat:@"Vị trí điểm đến %@ hiện tại có dông, nhiệt độ %.0f độ. Chú ý mang theo áo mưa và cẩn thận khi di chuyển.",place,temp];if(code==45||code==48)return [NSString stringWithFormat:@"Vị trí điểm đến %@ hiện tại có sương mù, nhiệt độ %.0f độ. Chú ý quan sát khi di chuyển.",place,temp];if(code>=71&&code<=77)return [NSString stringWithFormat:@"Vị trí điểm đến %@ hiện tại có tuyết, nhiệt độ %.0f độ. Chú ý khi di chuyển.",place,temp];if(code<=3)return [NSString stringWithFormat:@"Vị trí điểm đến %@ hiện tại có mây, nhiệt độ %.0f độ.",place,temp];return [NSString stringWithFormat:@"Thời tiết tại điểm đến %@, nhiệt độ %.0f độ.",place,temp];}
static AVSpeechSynthesisVoice *WSBVoice(void){AVSpeechSynthesisVoice *v=[AVSpeechSynthesisVoice voiceWithLanguage:@"vi-VN"];if(!v)v=[AVSpeechSynthesisVoice voiceWithLanguage:@"vi"];return v;}
static void WSBSpeakPayload(void){NSDictionary *p=[NSDictionary dictionaryWithContentsOfFile:kWSBPayloadPath];if(![p isKindOfClass:NSDictionary.class]){WSBLog(@"payload missing");return;}NSString *name=[p[@"name"] description];double temp=[p[@"temperature"] doubleValue];NSInteger code=[p[@"weather_code"] integerValue];NSString *sentence=WSBSentence(name,temp,code);dispatch_async(dispatch_get_main_queue(),^{NSError *err=nil;AVAudioSession *session=AVAudioSession.sharedInstance;BOOL ok=[session setCategory:AVAudioSessionCategoryPlayback mode:AVAudioSessionModeSpokenAudio options:AVAudioSessionCategoryOptionDuckOthers error:&err];WSBLog(@"audio category ok=%d error=%@",ok,err.localizedDescription?:@"none");err=nil;ok=[session setActive:YES error:&err];WSBLog(@"audio active ok=%d error=%@",ok,err.localizedDescription?:@"none");if(!gWSBSpeech)gWSBSpeech=[AVSpeechSynthesizer new];[gWSBSpeech stopSpeakingAtBoundary:AVSpeechBoundaryImmediate];AVSpeechUtterance *u=[AVSpeechUtterance speechUtteranceWithString:sentence];AVSpeechSynthesisVoice *voice=WSBVoice();if(voice)u.voice=voice;u.rate=.45;u.pitchMultiplier=1.0;u.volume=1.0;u.preUtteranceDelay=.18;WSBLog(@"speak voice=%@ sentence=%@",voice.language?:@"nil",sentence);[gWSBSpeech speakUtterance:u];});}
static void WSBStart(void){if(!WSBIsSpringBoard()||gWSBToken)return;int token=0;uint32_t s=notify_register_dispatch(kWSBWeatherNotify,&token,dispatch_get_main_queue(),^(__unused int incoming){WSBSpeakPayload();});if(s==NOTIFY_STATUS_OK){gWSBToken=token;WSBLog(@"receiver ready token=%d",token);}else WSBLog(@"receiver failed status=%u",s);}
%ctor{@autoreleasepool{if(!WSBIsSpringBoard())return;WSBLog(@"16.16 speech bridge loaded");WSBStart();}}
