name: Build VMLSpeedBubble

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-14

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Theos
        run: |
          export THEOS=$HOME/theos
          bash -c "$(curl -fsSL https://raw.githubusercontent.com/roothide/theos/master/bin/install-theos)"

      - name: Install Theos
        run: |
          export THEOS=$HOME/theos
          bash -c "$(curl -fsSL https://raw.githubusercontent.com/roothide/theos/master/bin/install-theos)"

      - name: Build RootHide package
        run: |
          export THEOS=$HOME/theos
          make clean package FINALPACKAGE=1

      - name: Build RootHide package
        run: |
          export THEOS=$HOME/theos
          make clean package FINALPACKAGE=1

      - name: Upload DEB
        uses: actions/upload-artifact@v4
        with:
          name: VMLSpeedBubble-RootHide
          path: packages/*.deb
