name: Build VMLSpeedBubble

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-14

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Theos + iOS 16.5 SDK
        run: |
          export THEOS=$HOME/theos

          curl -fsSL \
            https://raw.githubusercontent.com/roothide/theos/master/bin/install-theos \
            -o install-theos.sh

          sed -E -i '' '/get_sdks/d' install-theos.sh

          bash install-theos.sh

          mkdir -p $THEOS/sdks

          curl -L \
            https://github.com/theos/sdks/releases/latest/download/iPhoneOS16.5.sdk.tar.xz \
            -o $THEOS/sdks/iPhoneOS16.5.sdk.tar.xz

          xz -d $THEOS/sdks/iPhoneOS16.5.sdk.tar.xz

          tar -xf $THEOS/sdks/iPhoneOS16.5.sdk.tar \
            -C $THEOS/sdks

          rm $THEOS/sdks/iPhoneOS16.5.sdk.tar

          ls -la $THEOS/sdks

      - name: Build RootHide package
        run: |
          export THEOS=$HOME/theos
          make clean package FINALPACKAGE=1

      - name: Upload DEB
        uses: actions/upload-artifact@v4
        with:
          name: VMLSpeedBubble-RootHide
          path: packages/*.deb
